FROM docker.io/tensorflow/tensorflow:latest-gpu
# FROM stablebaselines/stable-baselines

RUN apt update
RUN apt install -y libopenmpi-dev git
# python3.11 python3.11-venv
# RUN apt install -y  libcufft10 libcublas11 libcudnn8

RUN apt install -y task-spooler htop nvtop btop python3.11 python3.11-venv libgl1 libglib2.0-0

